### ISSUE TITLE
Transfer ownership!

### ISSUE THREAD

**Issue by chancancode** [Kobzol/rust-delegate#33]
Since I am not really involved in maintaining this crate anymore, I wonder if any of the current maintainers would be interested in me transferring over the GitHub ownership (or make an org for it)? I don’t mind keeping it under my user, but if there is any interest just let me know and it will be happy to do it.

**Comment by Kobzol** [comment]
Hi, I'm probably the only currently active maintainer (although there are more  active contributors!). I don't think that creating an org is necessary, and this crate is probably not "foundational" enough to be moved under the official Rust crates org.

I'd be happy to take over the ownership, but at the same time I don't insist on it, we can also keep it as it is.

**Comment by chancancode** [comment]
I initiated the transfer! Should make it easier for you to manage collaborators and CI etc.

**Comment by Kobzol** [comment]
Thank you! It's very kind of you :) I have accepted the transfer, so this issue can now be closed I guess.
