### ISSUE TITLE
Bridging sync to async gap with delegate

### ISSUE THREAD

**Issue by kyku** [Kobzol/rust-delegate#38]
Hi,
Let's have a struct with a bunch of methods:

```rust
struct UserRepo { /* ... */ }

impl UserRepo {
  fn add() { /* ... */ }
  fn del() { /* ... */ }
}
```

Now we'd like to use this repository in asynchronous code where many workers need to access a single instance of the repository. To guard against race conditions we need to wrap the struct in a Mutex:

```rust
struct SharedUserRepo(tokio::sync::Mutex<UserRepo>)
```

Next step is to delegate `add` and `del` calls to a locked instance of UserRepo:

```rust
impl SharedUserRepo {
  delegate! {
    to self.0.lock().await {
     async fn add() { /* ... */ }
     async fn del() { /* ... */ }
    }
  }
}
```

But this code is rejected by rust, so the question is if this can be solved with current delegate or if some extension is needed (like `to_async` instead of `to`).

The delegated macro expands to this code, where the second await seems to be invalid:

```rust
#[inline(always)]
async fn add(&mut self) {
  self.0.lock().await.add().await;
}
```

**Comment by Kobzol** [comment]
Hi! That seems like a useful use-case. Please try this PR: https://github.com/Kobzol/rust-delegate/pull/39 with this code:
```rust
impl SharedUserRepo {
  delegate! {
    to self.0.lock().await {
     #[await(false)]
     async fn add() { /* ... */ }
     #[await(false)]
     async fn del() { /* ... */ }
    }
  }
}
```

You can use the code from the PR with this dependency specification in `Cargo.toml`:
```toml
[dependencies]
delegate = { git = "https://github.com/kobzol/rust-delegate", branch = "await-attribute" }
```

**Comment by kyku** [comment]
Works for me ™ ;-)

**Comment by Kobzol** [comment]
Great! I published a new version (`0.6.2`) with the attribute.

**Comment by kyku** [comment]
Would it be possible to support this attribute before the `to` block, like in:

```rust
delegate! {
  #[await(false)]
  to self.0.lock().await {
     async fn f1();
     // ...
     async fn fn();
  }
}
```

This would be equivalent of placing #[await(false)] before every fX() inside of the block.

**Comment by Kobzol** [comment]
I'll think about it. It definitely seems useful, but I don't want to enable it only for `#[await]`, if attributes are enabled on top of `to`, it should also work for other things, at least `#[into]` (not sure if `#[call]` makes sense here).

It will require some refactoring and I don't know how difficult it will be to parse. I'll experiment with it.
