### ISSUE TITLE
allow #[try_from] and #[try_into]

### ISSUE THREAD

**Issue by Leoyzen** [Kobzol/rust-delegate#42]
It is awesome to support TryFrom and TryInto.

In some case it is `unsafe` to just using `from` or `into`(especially there are some checking link utf8 bytes check).

**Comment by Kobzol** [comment]
Hi, do you have a concrete use-case that you could post here? It would help me understand better how should this work w.r.t. the return type (return `Result`? unwrap? etc.).

**Comment by Leoyzen** [comment]
@Kobzol 
I'm working on some case like ByteStr which just wrapping bytes::Bytes.
It is not safe just convert bytes(&[u8]) to string directly.We should do some checking work (check whether it is valid utf8 array).

But we want some useful function from Bytes like `split_off`, `split_to`.

```rust
pub struct ByteStr(Bytes);

impl TryFrom<Bytes> for ByteStr {
    ...
    fn try_from(v: Bytes) -> Result<Self, Self::Err> {
       // some checking
        let _ = std::str::from_utf8(v.as_ref)?;
        Ok(Self(v))
    }
}

impl ByteStr {
    pub fn unsafe from_bytes_unchecked(v: Bytes) -> Self;
    
    delegate! {
        to self.0 {
           // we do want `split_to` and return Self instead of Bytes
           // it is awesome using `try_into` or `from_bytes_unchecked` (it is safe because we just split a valid origin)
           #[try_into]
            pub fn split_to(&mut self, at: usize) -> Bytes
        }
    }
}
```

**Comment by Leoyzen** [comment]
Yeah that's nice.

Or some postprocess function could also be proposed as a solution.

Exp. `#[call(method,post=post_func)]`

Or func chain

Exp. `#[call(method, post_func)]`

The last func result should be returned.

**Comment by Leoyzen** [comment]
@Kobzol It works now, thank u.

In some scenario, the check is unnecessary(for example above, we already validate the utf8 str), we could just wrap it with `Self` as inner. I think it is much common scene, is it possible to do that right now(like `call(Self)`)?

```rust
pub struct ByteStr(Bytes);

impl TryFrom<Bytes> for ByteStr {
    ...
    fn try_from(v: Bytes) -> Result<Self, Self::Err> {
       // some checking
        let _ = std::str::from_utf8(v.as_ref)?;
        Ok(Self(v))
    }
}

impl ByteStr {
    pub unsafe fn from_bytes_unchecked(v: Bytes) -> Self;
    
    delegate! {
        to self.0 {
           // we already checked before, the sometimes the split is simple enough(like ascii)
          // it is unnecessary to check it again, we can just wrap it as inner
           #[call(Self)]
            pub fn split_to(&mut self, at: usize) -> ByteStr
        }
    }
}

```

**Comment by Kobzol** [comment]
It's not possible at the moment, but wrapping a an inner type of a newtype seems like a common use-case, I'll think about it. In any case, it's a different issue than `try_from`.

**Comment by Leoyzen** [comment]
@Kobzol Anyway,thanks u for your work.The issues can be closed now.
