### ISSUE TITLE
Compatability with async_trait

### ISSUE THREAD

**Issue by Ji-Xinyou** [Kobzol/rust-delegate#46]
When using `delegate!` under trait attributed by `#[async_trait]`, the expand order matters and it seems cannot compile.
IMO, only when `delegate!` expands before `#[async_trait]`, can this compile and work correctly.

e.g. this won't compile
```rust
#[async_trait]
impl Foo for Bar {
    delegate! {
        to self.inner {
            async fn baz(&self);
        }
    }
}
```

Is there a way to solve this problem?

**Comment by Kobzol** [comment]
I don't think that this is possible currently (https://stackoverflow.com/questions/62493492/is-is-possible-in-rust-to-invoke-a-macro-in-procedure-macro-code).

**Comment by Ji-Xinyou** [comment]
> I don't think that this is possible currently (https://stackoverflow.com/questions/62493492/is-is-possible-in-rust-to-invoke-a-macro-in-procedure-macro-code).

Thanks for answering! I guess this problem can only be solved when rust supports sort of macro expand ordering specifications.
