### ISSUE TITLE
Just unwrap

### ISSUE THREAD

**Issue by joshhansen** [Kobzol/rust-delegate#48]
I see an option to `unwrap` as part of `try_into`: `try_into(unwrap)`

But I'd like to just append an `.unwrap()` call directly - is this possible?

I'm delegating to a method that returns a `Result` whose only error case is guaranteed not to happen in the delegating struct, so I'd like to unwrap.

**Comment by Kobzol** [comment]
Hi, that's a good idea. I removed `#[try_into(unwrap)]` and added a separate `#[unwrap]` attribute in https://github.com/Kobzol/rust-delegate/pull/49. These attributes can now also be repeated and composed, so `#[try_into(unwrap)]` can now be achieved with
```
#[try_into]
#[unwrap]
```

Please try it and let me know if it works for you!
```
[dependencies]
delegate = { git = "https://github.com/kobzol/rust-delegate", branch = "unwrap" }
```

**Comment by joshhansen** [comment]
Awesome! That branch appears to work as expected, thanks for the quick action.

I wonder if a general mechanism for appending method calls might be useful. E.g. `#[method(clone)]` or `#[method(Cow::Borrowed)]`.

**Comment by Kobzol** [comment]
Probably, but to be honest I'm not sure how useful is to delegate such complex expressions, in general. Is this:
```rust
delegate! {
    to self.foo {
        #[unwrap]
        #[into]
        #[method(clone)]
        fn bar(&self, A) -> B;
    }
}
```
really better than
```rust
fn bar(&self, a: A) -> B {
    self.foo.bar(a).unwrap().into().clone()
}
```
?
