### ISSUE TITLE
Add attribute to the return value of all methods

### ISSUE THREAD

**Issue by momvart** [Kobzol/rust-delegate#51]
In one of my delegations, only and only `.into` should be applied to the result of the wrapped value so ended up with this:
```rust
delegate! {
    to self.0 {
        #[into]
        fn a<'a>(&mut self, x: T) -> R;

        #[into]
        fn b<'a>(&mut self, x: T) -> R;

        #[into]
        fn c<'a>(&mut self, x: T) -> R;

        // ...
    }
}
```
It would be great if we could apply the `into` attribute to all of them at once like:
```rust
delegate! {
    #[into]
    to self.0 {
        fn a<'a>(&mut self, x: T) -> R;
        fn b<'a>(&mut self, x: T) -> R;
        fn c<'a>(&mut self, x: T) -> R;
        // ...
    }
}
```

**Comment by Kobzol** [comment]
Hi, yeah, this is a good idea and have been on my TODO list for a time. I'll try to work on it tomorrow.

**Comment by Kobzol** [comment]
Good. I will merge it then, and release a new version soon (I'll also try to look at your other issue).
