### ISSUE TITLE
`no_std` support

### ISSUE THREAD

**Issue by RatCornu** [Kobzol/rust-delegate#65]
Hello ! I really like this carte but I cannot use it in its current version due to the use or `std`: is it planned to support `no_std` as well (with feature flags for exemple) ?

**Comment by Kobzol** [comment]
Hi, could you please send an example of a program that uses rust-delegate, and doesn't compile with no_std?

**Comment by RatCornu** [comment]
I tried to make a minimal example of my problem, but I didn't succeed to: after some checks, my previous problem was caused by something else and not by `delegate`, so everything is fine, sorry \^\^'

**Comment by Kobzol** [comment]
To provide a bit more context: this crate is a proc macro, so it using `std` shouldn't be a problem for `no_std` crates. Only the code generated by the macro shouldn't contain `std` references, which AFAIK it doesn't.

**Comment by apparentlymart** [comment]
Hello!

Sorry for re-awakening an old issue, but I notice that the `into` and `try_into` modifiers now generate references to `::std::convert::Into` and `::std::convert::TryInto` here:

https://github.com/Kobzol/rust-delegate/blob/868eaeef4658b387bce7ed22a60ba8d4821ab921/src/lib.rs#L865-L880

This _does_ make my `no_std` crate (which is not yet public, unfortunately) generate errors when using those modifiers:

```
failed to resolve: could not find `std` in the list of imported crates
```

I hand-wrote some delegating wrappers for my two functions that currently needed those annotations for now, so this isn't a big blocker for me but just wanted to raise it in case it's something that you might be open to change. As far as I can tell, changing the generated code to use `::core::convert::Into` and `::core::convert::TryInto` would be sufficient to make it work in both std and no-std crates.

**Comment by Kobzol** [comment]
Ooh, that's a great point, thanks! Could you please try [this PR](https://github.com/Kobzol/rust-delegate/pull/74)?

```toml
[dependencies]
delegate = { git = "https://github.com/kobzol/rust-delegate", branch = "into-core" }
```
