### ISSUE TITLE
Re-use documentation from delegated method

### ISSUE THREAD

**Issue by alpha-tango-kilo** [Kobzol/rust-delegate#67]
I wanted to use `delegate` to save the boilerplate of re-creating and re-documenting all the useful methods on the inner type for a crate API. I don't want to just copy-paste if I can avoid it

Would something like this be possible?

```rs
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Dictionary<'a>(IndexMap<&'a str, Value<'a>>);

impl<'a> Dictionary<'a> {
    delegate! {
        #[docs]
        to self.0 {
            pub fn clear(&mut self);
            pub fn get(&self, key: &str) -> Option<&Value<'a>>;
        }
    }
}
```

**Comment by Kobzol** [comment]
Hi, no, sadly this is not possible with the current procedural macro system of Rust. There is no way of accessing the docs of the target method from the place where the method is actually delegated. We would need reflection for that.

In theory, this could be possible with e.g. https://docs.rs/ambassador/latest/ambassador/, if you control the trait. But it does not seem to copy the docs at the moment.

**Comment by alpha-tango-kilo** [comment]
That's a shame, hopefully in the future perhaps then. Thanks for the fast response!
