### ISSUE TITLE
Suggestion: Delegate associated functions

### ISSUE THREAD

**Issue by huuff** [Kobzol/rust-delegate#71]
I'm currently writing a wrapper around https://github.com/akubera/bigdecimal-rs that ensures they have a specific precision:

```rust
pub struct PrecBigDecimal<const PLACES: usize>(BigDecimal);

impl<const PLACES: usize> From<BigDecimal> for PrecBigDecimal<PLACES> {
    fn from(bd: BigDecimal) -> Self {
        Self(bd.with_scale_round(PLACES as i64, RoundingMode::HalfEven))
    }
}
```

I'd love to be able to construct a `PrecBigDecimal` in the same ways I can construct a `BigDecimal`, but AFAIK there's no way to delegate associated functions:

```rust
impl<const PLACES: usize> PrecBigDecimal<PLACES> {
    delegate! {
        to BigDecimal {
            #[into]
            pub fn from_str(s: &str) -> Result<Self, ParseBigDecimalError>;
        }
    }
}
```

Would this be feasible?

Thanks for this awesome crate!

**Comment by Kobzol** [comment]
Hi, this should work fine. The problem in your example is that `Result<PrecBigDecimal, ParseBigDecimalError>` does not implement `From<Result<BigDecimal, ParseBigDecimalError>>`. If you would add that impl, it would compile. The problem with that is that you cannot add that impl because of orphan rules :)

**Comment by huuff** [comment]
You're right. I just hoped there were some blanket `impl` to cover my case and didn't think more about it. I just thought delegating to associated functions wasn't implemented because I haven't seen any example about it in the docs. Maybe we could add one?

Thank you

**Comment by Kobzol** [comment]
Good idea, added [here](https://github.com/Kobzol/rust-delegate/pull/73).
